
.section .text
.global _isr0
.type _isr0, @function
_isr0:
  cli
  pushl $0

  pushl $0
  jmp _isr_common_handler
.size _isr0, . - _isr0


.section .text
.global _isr1
.type _isr1, @function
_isr1:
  cli
  pushl $0

  pushl $1
  jmp _isr_common_handler
.size _isr1, . - _isr1


.section .text
.global _isr2
.type _isr2, @function
_isr2:
  cli
  pushl $0

  pushl $2
  jmp _isr_common_handler
.size _isr2, . - _isr2


.section .text
.global _isr3
.type _isr3, @function
_isr3:
  cli
  pushl $0

  pushl $3
  jmp _isr_common_handler
.size _isr3, . - _isr3


.section .text
.global _isr4
.type _isr4, @function
_isr4:
  cli
  pushl $0

  pushl $4
  jmp _isr_common_handler
.size _isr4, . - _isr4


.section .text
.global _isr5
.type _isr5, @function
_isr5:
  cli
  pushl $0

  pushl $5
  jmp _isr_common_handler
.size _isr5, . - _isr5


.section .text
.global _isr6
.type _isr6, @function
_isr6:
  cli
  pushl $0

  pushl $6
  jmp _isr_common_handler
.size _isr6, . - _isr6


.section .text
.global _isr7
.type _isr7, @function
_isr7:
  cli
  pushl $0

  pushl $7
  jmp _isr_common_handler
.size _isr7, . - _isr7


.section .text
.global _isr8
.type _isr8, @function
_isr8:
  cli
  

  pushl $8
  jmp _isr_common_handler
.size _isr8, . - _isr8


.section .text
.global _isr9
.type _isr9, @function
_isr9:
  cli
  pushl $0

  pushl $9
  jmp _isr_common_handler
.size _isr9, . - _isr9


.section .text
.global _isr10
.type _isr10, @function
_isr10:
  cli
  

  pushl $10
  jmp _isr_common_handler
.size _isr10, . - _isr10


.section .text
.global _isr11
.type _isr11, @function
_isr11:
  cli
  

  pushl $11
  jmp _isr_common_handler
.size _isr11, . - _isr11


.section .text
.global _isr12
.type _isr12, @function
_isr12:
  cli
  

  pushl $12
  jmp _isr_common_handler
.size _isr12, . - _isr12


.section .text
.global _isr13
.type _isr13, @function
_isr13:
  cli
  

  pushl $13
  jmp _isr_common_handler
.size _isr13, . - _isr13


.section .text
.global _isr14
.type _isr14, @function
_isr14:
  cli
  

  pushl $14
  jmp _isr_common_handler
.size _isr14, . - _isr14


.section .text
.global _isr15
.type _isr15, @function
_isr15:
  cli
  pushl $0

  pushl $15
  jmp _isr_common_handler
.size _isr15, . - _isr15


.section .text
.global _isr16
.type _isr16, @function
_isr16:
  cli
  pushl $0

  pushl $16
  jmp _isr_common_handler
.size _isr16, . - _isr16


.section .text
.global _isr17
.type _isr17, @function
_isr17:
  cli
  

  pushl $17
  jmp _isr_common_handler
.size _isr17, . - _isr17


.section .text
.global _isr18
.type _isr18, @function
_isr18:
  cli
  pushl $0

  pushl $18
  jmp _isr_common_handler
.size _isr18, . - _isr18


.section .text
.global _isr19
.type _isr19, @function
_isr19:
  cli
  pushl $0

  pushl $19
  jmp _isr_common_handler
.size _isr19, . - _isr19


.section .text
.global _isr20
.type _isr20, @function
_isr20:
  cli
  pushl $0

  pushl $20
  jmp _isr_common_handler
.size _isr20, . - _isr20


.section .text
.global _isr21
.type _isr21, @function
_isr21:
  cli
  pushl $0

  pushl $21
  jmp _isr_common_handler
.size _isr21, . - _isr21


.section .text
.global _isr22
.type _isr22, @function
_isr22:
  cli
  pushl $0

  pushl $22
  jmp _isr_common_handler
.size _isr22, . - _isr22


.section .text
.global _isr23
.type _isr23, @function
_isr23:
  cli
  pushl $0

  pushl $23
  jmp _isr_common_handler
.size _isr23, . - _isr23


.section .text
.global _isr24
.type _isr24, @function
_isr24:
  cli
  pushl $0

  pushl $24
  jmp _isr_common_handler
.size _isr24, . - _isr24


.section .text
.global _isr25
.type _isr25, @function
_isr25:
  cli
  pushl $0

  pushl $25
  jmp _isr_common_handler
.size _isr25, . - _isr25


.section .text
.global _isr26
.type _isr26, @function
_isr26:
  cli
  pushl $0

  pushl $26
  jmp _isr_common_handler
.size _isr26, . - _isr26


.section .text
.global _isr27
.type _isr27, @function
_isr27:
  cli
  pushl $0

  pushl $27
  jmp _isr_common_handler
.size _isr27, . - _isr27


.section .text
.global _isr28
.type _isr28, @function
_isr28:
  cli
  pushl $0

  pushl $28
  jmp _isr_common_handler
.size _isr28, . - _isr28


.section .text
.global _isr29
.type _isr29, @function
_isr29:
  cli
  pushl $0

  pushl $29
  jmp _isr_common_handler
.size _isr29, . - _isr29


.section .text
.global _isr30
.type _isr30, @function
_isr30:
  cli
  

  pushl $30
  jmp _isr_common_handler
.size _isr30, . - _isr30


.section .text
.global _isr31
.type _isr31, @function
_isr31:
  cli
  pushl $0

  pushl $31
  jmp _isr_common_handler
.size _isr31, . - _isr31


.section .text
.global _isr32
.type _isr32, @function
_isr32:
  cli
  pushl $0

  pushl $32
  jmp _isr_common_handler
.size _isr32, . - _isr32


.section .text
.global _isr33
.type _isr33, @function
_isr33:
  cli
  pushl $0

  pushl $33
  jmp _isr_common_handler
.size _isr33, . - _isr33


.section .text
.global _isr34
.type _isr34, @function
_isr34:
  cli
  pushl $0

  pushl $34
  jmp _isr_common_handler
.size _isr34, . - _isr34


.section .text
.global _isr35
.type _isr35, @function
_isr35:
  cli
  pushl $0

  pushl $35
  jmp _isr_common_handler
.size _isr35, . - _isr35


.section .text
.global _isr36
.type _isr36, @function
_isr36:
  cli
  pushl $0

  pushl $36
  jmp _isr_common_handler
.size _isr36, . - _isr36


.section .text
.global _isr37
.type _isr37, @function
_isr37:
  cli
  pushl $0

  pushl $37
  jmp _isr_common_handler
.size _isr37, . - _isr37


.section .text
.global _isr38
.type _isr38, @function
_isr38:
  cli
  pushl $0

  pushl $38
  jmp _isr_common_handler
.size _isr38, . - _isr38


.section .text
.global _isr39
.type _isr39, @function
_isr39:
  cli
  pushl $0

  pushl $39
  jmp _isr_common_handler
.size _isr39, . - _isr39


.section .text
.global _isr40
.type _isr40, @function
_isr40:
  cli
  pushl $0

  pushl $40
  jmp _isr_common_handler
.size _isr40, . - _isr40


.section .text
.global _isr41
.type _isr41, @function
_isr41:
  cli
  pushl $0

  pushl $41
  jmp _isr_common_handler
.size _isr41, . - _isr41


.section .text
.global _isr42
.type _isr42, @function
_isr42:
  cli
  pushl $0

  pushl $42
  jmp _isr_common_handler
.size _isr42, . - _isr42


.section .text
.global _isr43
.type _isr43, @function
_isr43:
  cli
  pushl $0

  pushl $43
  jmp _isr_common_handler
.size _isr43, . - _isr43


.section .text
.global _isr44
.type _isr44, @function
_isr44:
  cli
  pushl $0

  pushl $44
  jmp _isr_common_handler
.size _isr44, . - _isr44


.section .text
.global _isr45
.type _isr45, @function
_isr45:
  cli
  pushl $0

  pushl $45
  jmp _isr_common_handler
.size _isr45, . - _isr45


.section .text
.global _isr46
.type _isr46, @function
_isr46:
  cli
  pushl $0

  pushl $46
  jmp _isr_common_handler
.size _isr46, . - _isr46


.section .text
.global _isr47
.type _isr47, @function
_isr47:
  cli
  pushl $0

  pushl $47
  jmp _isr_common_handler
.size _isr47, . - _isr47



.section .text
.global _isr128
.type _isr128, @function
_isr128:
  cli
  pushl $0

  pushl $128
  jmp _isr_common_handler
.size _isr128, . - _isr128



_isr_common_handler:
  pusha
  pushw %ds
  pushw %es
  pushw %fs
  pushw %gs

  movw $0x18, %ax
  movw %ax, %ds
  movw %ax, %es
  movw %ax, %fs
  movw %ax, %gs
  movl %esp, %eax
  pushl %eax
  movl $_arch_interrupt_handler, %eax
  call *%eax
  popl %eax

  popw %gs
  popw %fs
  popw %es
  popw %ds
  popa

  addl $8, %esp
  iret
